// first array is word, second is hint
export const wordList = {
  everydayObjects: [
    [
      "spoon",
      "coffee mug",
      "cutting board",
      "paper towel roll",
      "can opener",
      "dish sponge",
      "zip-top bag",
      "tea kettle",
      "salt shaker",
      "tupperware lid",
      "oven mitt",
      "cheese grater",
      "blender",
      "measuring cup",
      "chip clip",
      "toothbrush",
      "nail clipper",
      "shampoo bottle",
      "toilet plunger",
      "bath mat",
      "cotton swab",
      "dental floss",
      "hand soap dispenser",
      "shower curtain ring",
      "tweezers",
      "hair tie",
      "razor",
      "washcloth",
      "contact lens case",
      "clothes hanger",
      "sock",
      "belt",
      "alarm clock",
      "pillowcase",
      "shoe box",
      "laundry basket",
      "button",
      "zipper",
      "flashlight",
      "phone charger",
      "bedside lamp",
      "coin from jeans pocket",
      "TV remote",
      "coaster",
      "throw blanket",
      "light switch",
      "extension cord",
      "house key",
      "doorstop",
      "picture frame",
      "bookmark",
      "sticky note pad",
      "pen cap",
      "earbuds",
      "candle",
      "plant pot",
      "stapler",
      "binder clip",
      "rubber band",
      "USB stick",
      "sticky tack",
      "highlighter",
      "notebook",
      "mouse pad",
      "hole punch",
      "whiteboard marker",
      "paper clip",
      "envelope",
      "tape dispenser",
      "desk fan",
      "screwdriver",
      "duct tape",
      "paintbrush",
      "AAA battery",
      "zip tie",
      "garden hose nozzle",
      "work gloves",
      "level",
      "WD-40 can",
      "measuring tape",
      "bungee cord",
      "flowerpot",
      "bike pump",
      "receipt",
      "wallet",
      "sunglasses",
      "reusable shopping bag",
      "lint roller",
      "hand sanitizer",
      "gum wrapper",
      "car keys",
      "band-aid",
      "lip balm",
      "headphones case",
      "fork",
      "spatula",
      "whisk",
      "colander",
      "peeler",
      "garlic press",
      "pizza cutter",
      "ice cube tray",
      "wine opener",
      "spice jar",
      "dish rack",
      "microwave plate",
      "toaster",
      "frying pan",
      "pot lid",
      "butter dish",
      "egg timer",
      "apron",
      "loofah",
      "bathrobe",
      "toilet brush",
      "plunger",
      "scale",
      "towel rack",
      "shower cap",
      "pumice stone",
      "q-tips box",
      "mouthwash",
      "hairbrush",
      "shoe horn",
      "umbrella",
      "scarf",
      "watch",
      "earring",
      "necklace",
      "ring",
      "safety pin",
      "sewing needle",
      "thread spool",
      "lint brush",
      "slippers",
      "night light",
      "curtain rod",
      "blind cord",
      "drawer knob",
      "rug",
      "game controller",
      "DVD case",
      "magazine",
      "newspaper",
      "puzzle piece",
      "board game box",
      "playing cards",
      "dice",
      "yoga mat",
      "dumbbell",
      "basketball",
      "frisbee",
      "dog leash",
      "pet bowl",
      "bird feeder",
      "scissors",
      "glue stick",
      "ruler",
      "calculator",
      "calendar",
      "eraser",
      "push pin",
      "thumb tack",
      "index card",
      "file folder",
      "label maker",
      "webcam",
      "keyboard",
      "computer mouse",
      "speaker",
      "power strip",
      "hammer",
      "wrench",
      "pliers",
      "nails",
      "screws",
      "sandpaper",
      "drill bit",
      "tape measure",
      "caulk gun",
      "paint roller",
      "drop cloth",
      "tool belt",
      "rake",
      "shovel",
      "watering can",
      "gloves",
      "knee pad",
      "hose",
      "sprinkler",
      "trash can",
      "recycling bin",
      "broom",
      "dustpan",
      "mop",
      "bucket",
      "feather duster",
      "light bulb",
      "fuse",
      "smoke detector",
      "fire extinguisher",
      "first aid kit",
      "thermometer",
      "magnifying glass",
      "binoculars",
      "compass",
      "map",
      "backpack",
      "lunch box",
      "water bottle",
      "thermos",
      "ice pack",
      "bicycle lock",
      "helmet",
      "knee pads",
      "skateboard",
      "scooter",
      "postcard",
      "gift wrap",
      "ribbon",
      "balloon",
      "party hat",
      "chopsticks",
      "soy sauce packet",
      "ketchup packet",
      "sugar packet",
      "straw",
      "napkin",
      "toothpick",
      "menu",
      "takeout container",
      "aluminum foil",
      "plastic wrap",
      "parchment paper",
      "coffee filter",
      "tea bag",
      "strainer",
    ],
    [
      "scoop",
      "caffeine",
      "chop",
      "spill",
      "tin",
      "scrub",
      "seal",
      "whistle",
      "season",
      "cover",
      "heat",
      "shred",
      "puree",
      "volume",
      "crimp",
      "bristle",
      "trim",
      "lather",
      "suction",
      "drip",
      "swab",
      "thread",
      "pump",
      "hoop",
      "pluck",
      "loop",
      "blade",
      "square",
      "eyes",
      "shoulder",
      "foot",
      "waist",
      "wake",
      "fabric",
      "cardboard",
      "dirty",
      "fasten",
      "teeth",
      "beam",
      "juice",
      "glow",
      "forgotten",
      "channel",
      "ring",
      "warm",
      "click",
      "length",
      "access",
      "wedge",
      "display",
      "page",
      "square",
      "tip",
      "sound",
      "wax",
      "dirt",
      "clamp",
      "grip",
      "stretch",
      "memory",
      "mount",
      "neon",
      "bound",
      "glide",
      "perforate",
      "erase",
      "bend",
      "mail",
      "strip",
      "breeze",
      "twist",
      "silver",
      "bristle",
      "power",
      "bind",
      "spray",
      "grip",
      "bubble",
      "squeak",
      "extend",
      "elastic",
      "soil",
      "inflate",
      "proof",
      "leather",
      "shade",
      "carry",
      "fuzz",
      "gel",
      "chew",
      "jingle",
      "adhesive",
      "wax",
      "shell",
      "stab",
      "flip",
      "foam",
      "drain",
      "peel",
      "crush",
      "slice",
      "freeze",
      "cork",
      "flavor",
      "dry",
      "spin",
      "brown",
      "sizzle",
      "cap",
      "dairy",
      "ring",
      "stain",
      "exfoliate",
      "terry",
      "bristle",
      "vacuum",
      "weight",
      "hang",
      "plastic",
      "stone",
      "cardboard",
      "mint",
      "tangle",
      "slide",
      "dome",
      "wrap",
      "tick",
      "dangle",
      "chain",
      "circle",
      "temporary",
      "point",
      "wind",
      "sweater",
      "soft",
      "dim",
      "suspend",
      "pull",
      "grab",
      "weave",
      "buttons",
      "plastic",
      "gloss",
      "print",
      "jigsaw",
      "cardboard",
      "shuffle",
      "roll",
      "stretch",
      "iron",
      "bounce",
      "throw",
      "walk",
      "kibble",
      "seeds",
      "snip",
      "stick",
      "straight",
      "math",
      "date",
      "mistake",
      "board",
      "sharp",
      "note",
      "manila",
      "adhesive",
      "eye",
      "qwerty",
      "click",
      "boom",
      "outlet",
      "bang",
      "torque",
      "grip",
      "metal",
      "spiral",
      "grit",
      "bore",
      "flex",
      "caulk",
      "coat",
      "canvas",
      "waist",
      "leaves",
      "dirt",
      "pour",
      "fabric",
      "cushion",
      "snake",
      "oscillate",
      "waste",
      "sort",
      "sweep",
      "catch",
      "wet",
      "carry",
      "tickle",
      "filament",
      "blow",
      "beep",
      "red",
      "gauze",
      "mercury",
      "enlarge",
      "distance",
      "north",
      "paper",
      "shoulder",
      "meal",
      "hydrate",
      "insulate",
      "cold",
      "secure",
      "skull",
      "scrape",
      "roll",
      "kick",
      "vacation",
      "surprise",
      "bow",
      "helium",
      "cone",
      "pair",
      "umami",
      "tomato",
      "sweet",
      "suck",
      "dab",
      "wood",
      "list",
      "leftover",
      "metal",
      "cling",
      "baking",
      "drip",
      "steep",
      "sift",
    ],
  ],
  foodsAndDrinks: [
    [
      "pizza",
      "hamburger",
      "sushi",
      "taco",
      "spaghetti",
      "pancake",
      "waffle",
      "croissant",
      "bagel",
      "donut",
      "apple",
      "banana",
      "orange",
      "strawberry",
      "watermelon",
      "carrot",
      "broccoli",
      "potato",
      "tomato",
      "lettuce",
      "cheddar cheese",
      "yogurt",
      "ice cream",
      "butter",
      "egg",
      "bacon",
      "chicken nugget",
      "steak",
      "salmon",
      "shrimp",
      "rice",
      "bread",
      "cereal",
      "oatmeal",
      "granola",
      "peanut butter",
      "jelly",
      "honey",
      "syrup",
      "ketchup",
      "coffee",
      "tea",
      "milk",
      "orange juice",
      "apple juice",
      "lemonade",
      "soda",
      "water",
      "beer",
      "wine",
      "hot chocolate",
      "smoothie",
      "milkshake",
      "energy drink",
      "coconut water",
      "cookie",
      "brownie",
      "cake",
      "pie",
      "muffin",
      "popcorn",
      "chips",
      "pretzel",
      "cracker",
      "trail mix",
      "salad",
      "soup",
      "sandwich",
      "burrito",
      "ramen",
      "dumpling",
      "spring roll",
      "curry",
      "lasagna",
      "chili",
      "avocado",
      "blueberry",
      "pineapple",
      "mango",
      "grape",
      "mushroom",
      "onion",
      "garlic",
      "pepper",
      "cucumber",
      "almond",
      "cashew",
      "walnut",
      "peanut",
      "pistachio",
      "chocolate bar",
      "lollipop",
      "gummy bear",
      "marshmallow",
      "cotton candy",
      "french fries",
      "onion rings",
      "mozzarella stick",
      "chicken wing",
      "nachos",
      "soy sauce",
      "hot sauce",
      "mustard",
      "mayonnaise",
      "barbecue sauce",
      "espresso",
      "latte",
      "cappuccino",
      "matcha",
      "kombucha",
      "bagel",
      "biscuit",
      "scone",
      "muffin",
      "toast",
      "pho",
      "pad thai",
      "fried rice",
      "lo mein",
      "bibimbap",
      "quesadilla",
      "enchilada",
      "tamale",
      "churro",
      "flan",
      "hummus",
      "falafel",
      "pita",
      "gyro",
      "baklava",
      "gnocchi",
      "risotto",
      "ravioli",
      "focaccia",
      "tiramisu",
      "kimchi",
      "bulgogi",
      "miso soup",
      "tempura",
      "mochi",
      "guacamole",
      "salsa",
      "tortilla",
      "plantain",
      "ceviche",
      "cheesecake",
      "pudding",
      "jello",
      "custard",
      "gelato",
      "espresso",
      "americano",
      "mocha",
      "chai",
      "boba",
      "sirloin",
      "ribeye",
      "brisket",
      "sausage",
      "ham",
      "turkey",
      "duck",
      "lamb",
      "crab",
      "lobster",
      "clam chowder",
      "tomato soup",
      "chicken noodle soup",
      "miso",
      "gazpacho",
      "kiwi",
      "peach",
      "plum",
      "cherry",
      "pear",
      "cantaloupe",
      "honeydew",
      "papaya",
      "fig",
      "pomegranate",
      "kale",
      "spinach",
      "cabbage",
      "asparagus",
      "zucchini",
      "eggplant",
      "beet",
      "radish",
      "celery",
      "corn",
      "pistachio ice cream",
      "sorbet",
      "frozen yogurt",
      "popsicle",
      "snow cone",
      "ginger ale",
      "root beer",
      "cola",
      "sparkling water",
      "tonic water",
      "whiskey",
      "vodka",
      "rum",
      "tequila",
      "gin",
    ],
    [
      "slice",
      "patty",
      "raw",
      "shell",
      "noodle",
      "stack",
      "grid",
      "crescent",
      "hole",
      "glaze",
      "red",
      "peel",
      "citrus",
      "seed",
      "rind",
      "crunch",
      "tree",
      "starch",
      "sauce",
      "leaf",
      "yellow",
      "culture",
      "cold",
      "spread",
      "shell",
      "sizzle",
      "nugget",
      "grill",
      "pink",
      "curly",
      "grain",
      "loaf",
      "bowl",
      "mush",
      "cluster",
      "sticky",
      "spread",
      "bee",
      "tree",
      "tomato",
      "bitter",
      "steep",
      "white",
      "pulp",
      "cloudy",
      "sour",
      "fizz",
      "clear",
      "hops",
      "grape",
      "winter",
      "blend",
      "thick",
      "caffeine",
      "tropical",
      "crumb",
      "fudge",
      "frosting",
      "crust",
      "top",
      "kernel",
      "crisp",
      "knot",
      "square",
      "hike",
      "bowl",
      "spoon",
      "bread",
      "wrap",
      "broth",
      "pocket",
      "wrapper",
      "spice",
      "layer",
      "beans",
      "green",
      "tiny",
      "crown",
      "pit",
      "vine",
      "fungus",
      "layer",
      "clove",
      "heat",
      "water",
      "oval",
      "curve",
      "brain",
      "shell",
      "split",
      "melt",
      "stick",
      "chew",
      "fluff",
      "spun",
      "salt",
      "circle",
      "pull",
      "bone",
      "melt",
      "umami",
      "fire",
      "yellow",
      "white",
      "smoke",
      "shot",
      "foam",
      "froth",
      "green",
      "ferment",
      "round",
      "flaky",
      "stone",
      "crumb",
      "crisp",
      "broth",
      "noodle",
      "wok",
      "tangle",
      "stone",
      "melt",
      "sauce",
      "husk",
      "cinnamon",
      "wobble",
      "chickpea",
      "ball",
      "pocket",
      "spit",
      "syrup",
      "pillow",
      "creamy",
      "square",
      "flat",
      "coffee",
      "ferment",
      "marinate",
      "soy",
      "batter",
      "pillow",
      "mash",
      "dip",
      "flat",
      "fry",
      "lime",
      "wedge",
      "set",
      "wobble",
      "pour",
      "italian",
      "concentrate",
      "dilute",
      "chocolate",
      "spice",
      "pearl",
      "cow",
      "marble",
      "smoke",
      "link",
      "pink",
      "gobble",
      "quack",
      "wool",
      "claw",
      "tail",
      "creamy",
      "red",
      "chicken",
      "ferment",
      "cold",
      "fuzzy",
      "pit",
      "stone",
      "stem",
      "bell",
      "net",
      "green",
      "orange",
      "seeds",
      "jewel",
      "curly",
      "flat",
      "head",
      "spear",
      "green",
      "purple",
      "root",
      "spicy",
      "string",
      "yellow",
      "green",
      "fruit",
      "tangy",
      "stick",
      "shave",
      "ginger",
      "herb",
      "cola",
      "bubble",
      "quinine",
      "amber",
      "clear",
      "sugar",
      "agave",
      "juniper",
    ],
  ],
  animalsAndPlants: [
    [
      "lion",
      "tiger",
      "elephant",
      "giraffe",
      "zebra",
      "kangaroo",
      "koala",
      "panda",
      "sloth",
      "gorilla",
      "chimpanzee",
      "orangutan",
      "wolf",
      "fox",
      "bear",
      "polar bear",
      "grizzly bear",
      "raccoon",
      "otter",
      "beaver",
      "squirrel",
      "chipmunk",
      "hedgehog",
      "porcupine",
      "skunk",
      "deer",
      "moose",
      "elk",
      "bison",
      "buffalo",
      "horse",
      "cow",
      "pig",
      "sheep",
      "goat",
      "chicken",
      "duck",
      "goose",
      "turkey",
      "peacock",
      "penguin",
      "ostrich",
      "flamingo",
      "eagle",
      "hawk",
      "owl",
      "parrot",
      "crow",
      "raven",
      "seagull",
      "sparrow",
      "robin",
      "cardinal",
      "bluejay",
      "hummingbird",
      "bat",
      "dolphin",
      "whale",
      "shark",
      "octopus",
      "squid",
      "jellyfish",
      "starfish",
      "crab",
      "lobster",
      "shrimp",
      "clam",
      "oyster",
      "snail",
      "slug",
      "frog",
      "toad",
      "turtle",
      "tortoise",
      "snake",
      "python",
      "cobra",
      "rattlesnake",
      "lizard",
      "gecko",
      "iguana",
      "chameleon",
      "crocodile",
      "alligator",
      "komodo dragon",
      "butterfly",
      "moth",
      "bee",
      "wasp",
      "ant",
      "ladybug",
      "dragonfly",
      "grasshopper",
      "cricket",
      "beetle",
      "spider",
      "scorpion",
      "centipede",
      "millipede",
      "worm",
      "leech",
      "mosquito",
      "fly",
      "cockroach",
      "termite",
      "cat",
      "dog",
      "hamster",
      "guinea pig",
      "rabbit",
      "ferret",
      "mouse",
      "rat",
      "goldfish",
      "betta fish",
      "oak tree",
      "maple tree",
      "pine tree",
      "palm tree",
      "birch tree",
      "willow tree",
      "redwood",
      "sequoia",
      "baobab",
      "bamboo",
      "cactus",
      "succulent",
      "aloe vera",
      "venus flytrap",
      "pitcher plant",
      "sunflower",
      "rose",
      "tulip",
      "daisy",
      "lily",
      "orchid",
      "daffodil",
      "lavender",
      "marigold",
      "chrysanthemum",
      "ivy",
      "fern",
      "moss",
      "seaweed",
      "kelp",
      "coral",
      "mushroom",
      "toadstool",
      "morel",
      "shiitake",
      "oyster mushroom",
      "portobello",
      "truffle",
      "lichen",
      "mold",
      "corn",
      "wheat",
      "rice",
      "barley",
      "oats",
      "sugarcane",
      "cotton",
      "tobacco",
      "coffee plant",
      "tea plant",
      "cocoa tree",
      "vanilla orchid",
      "rubber tree",
      "basil",
      "mint",
      "rosemary",
      "thyme",
      "oregano",
      "sage",
      "parsley",
      "cilantro",
      "dill",
      "chives",
      "garlic plant",
      "onion plant",
      "ginger root",
      "turmeric",
      "carrot plant",
      "potato plant",
      "sweet potato",
      "pumpkin vine",
      "squash",
      "zucchini plant",
      "cucumber vine",
      "watermelon vine",
      "strawberry plant",
      "blueberry bush",
      "raspberry bush",
      "blackberry bush",
      "grapevine",
      "apple tree",
      "pear tree",
      "peach tree",
      "cherry tree",
      "plum tree",
      "lemon tree",
      "lime tree",
      "orange tree",
      "banana tree",
      "coconut palm",
      "pineapple plant",
      "mango tree",
      "avocado tree",
      "olive tree",
      "fig tree",
      "date palm",
      "pomegranate tree",
      "kiwi vine",
      "papaya tree",
      "guava tree",
      "cheetah",
      "leopard",
      "jaguar",
      "panther",
      "lynx",
      "cougar",
      "bobcat",
      "hyena",
      "jackal",
      "coyote",
      "dingo",
      "wolverine",
      "badger",
      "weasel",
      "mink",
      "meerkat",
      "mongoose",
      "lemur",
      "sloth bear",
      "sun bear",
      "tapir",
      "rhino",
      "hippo",
      "warthog",
      "antelope",
      "gazelle",
      "impala",
      "wildebeest",
      "okapi",
      "llama",
      "alpaca",
      "camel",
      "dromedary",
      "yak",
      "water buffalo",
      "armadillo",
      "anteater",
      "pangolin",
      "platypus",
      "echidna",
      "wallaby",
      "wombat",
      "tasmanian devil",
      "quokka",
      "dingo",
      "vulture",
      "condor",
      "falcon",
      "kestrel",
      "peregrine",
      "albatross",
      "pelican",
      "swan",
      "crane",
      "stork",
      "heron",
      "ibis",
      "kingfisher",
      "woodpecker",
      "toucan",
      "macaw",
      "cockatoo",
      "canary",
      "finch",
      "peafowl",
      "salmon",
      "trout",
      "bass",
      "tuna",
      "swordfish",
      "eel",
      "catfish",
      "pike",
      "carp",
      "koi",
      "seahorse",
      "stingray",
      "manta ray",
      "pufferfish",
      "anglerfish",
      "piranha",
      "barracuda",
      "clownfish",
      "angelfish",
      "guppy",
      "salamander",
      "newt",
      "axolotl",
      "chameleon",
      "anole",
      "skink",
      "monitor lizard",
      "gila monster",
      "horned lizard",
      "frilled lizard",
      "anaconda",
      "boa constrictor",
      "viper",
      "mamba",
      "taipan",
      "tarantula",
      "black widow",
      "brown recluse",
      "daddy longlegs",
      "silkworm",
    ],
    [
      "mane",
      "stripe",
      "trunk",
      "neck",
      "stripe",
      "pouch",
      "eucalyptus",
      "bamboo",
      "slow",
      "chest",
      "tool",
      "orange",
      "howl",
      "sly",
      "hibernate",
      "arctic",
      "fish",
      "mask",
      "slide",
      "dam",
      "acorn",
      "cheek",
      "spine",
      "quill",
      "spray",
      "antler",
      "paddle",
      "bugle",
      "hump",
      "horn",
      "gallop",
      "moo",
      "oink",
      "wool",
      "climb",
      "cluck",
      "quack",
      "honk",
      "gobble",
      "fan",
      "tuxedo",
      "kick",
      "pink",
      "soar",
      "talon",
      "hoot",
      "mimic",
      "caw",
      "black",
      "beach",
      "chirp",
      "red",
      "crest",
      "blue",
      "hover",
      "echo",
      "click",
      "blow",
      "fin",
      "eight",
      "ten",
      "sting",
      "star",
      "pinch",
      "claw",
      "swim",
      "shell",
      "pearl",
      "spiral",
      "slime",
      "hop",
      "wart",
      "shell",
      "dome",
      "slither",
      "squeeze",
      "hood",
      "rattle",
      "tongue",
      "sticky",
      "spike",
      "color",
      "snap",
      "tooth",
      "dragon",
      "flutter",
      "dust",
      "buzz",
      "sting",
      "march",
      "spots",
      "glass",
      "leap",
      "chirp",
      "shell",
      "web",
      "sting",
      "legs",
      "thousand",
      "dirt",
      "suck",
      "bite",
      "buzz",
      "scurry",
      "wood",
      "purr",
      "bark",
      "wheel",
      "squeak",
      "hop",
      "mask",
      "scurry",
      "scurry",
      "bowl",
      "flair",
      "acorn",
      "syrup",
      "needle",
      "tropical",
      "white",
      "weep",
      "tall",
      "giant",
      "bottle",
      "hollow",
      "spike",
      "fleshy",
      "gel",
      "snap",
      "pitcher",
      "face",
      "thorn",
      "cup",
      "white",
      "trumpet",
      "wax",
      "trumpet",
      "purple",
      "gold",
      "mum",
      "climb",
      "spore",
      "carpet",
      "ocean",
      "forest",
      "reef",
      "cap",
      "spot",
      "brain",
      "umami",
      "cluster",
      "gill",
      "earthy",
      "crust",
      "fuzzy",
      "kernel",
      "gold",
      "grain",
      "beard",
      "flake",
      "sweet",
      "boll",
      "leaf",
      "bean",
      "leaf",
      "pod",
      "bean",
      "latex",
      "pesto",
      "cool",
      "needle",
      "tiny",
      "fuzzy",
      "furry",
      "flat",
      "feather",
      "frond",
      "hollow",
      "bulb",
      "layer",
      "knob",
      "root",
      "orange",
      "tuber",
      "orange",
      "tendril",
      "gourd",
      "green",
      "prickle",
      "seed",
      "runner",
      "shrub",
      "cane",
      "bramble",
      "vine",
      "orchard",
      "bell",
      "fuzzy",
      "pair",
      "stone",
      "yellow",
      "green",
      "round",
      "tropical",
      "hair",
      "crown",
      "stone",
      "pit",
      "brine",
      "split",
      "cluster",
      "seeds",
      "hair",
      "flesh",
      "seeds",
      "tear",
      "spot",
      "rosette",
      "black",
      "tuft",
      "scream",
      "stump",
      "laugh",
      "night",
      "yip",
      "wild",
      "musky",
      "stripe",
      "snake",
      "fur",
      "mob",
      "snake",
      "ghost",
      "honey",
      "nectar",
      "snout",
      "horn",
      "river",
      "tusk",
      "horn",
      "spring",
      "jump",
      "stripe",
      "tongue",
      "wool",
      "fleece",
      "hump",
      "one",
      "grunt",
      "swamp",
      "ball",
      "tongue",
      "scale",
      "egg",
      "spike",
      "hop",
      "cube",
      "scream",
      "smile",
      "wild",
      "carcass",
      "bald",
      "stoop",
      "hover",
      "fast",
      "glide",
      "pouch",
      "elegant",
      "dance",
      "baby",
      "spear",
      "spoon",
      "dive",
      "drum",
      "bill",
      "plume",
      "crest",
      "yellow",
      "stripe",
      "train",
      "run",
      "stream",
      "mouth",
      "silver",
      "bill",
      "snake",
      "whisker",
      "tooth",
      "scale",
      "scale",
      "upright",
      "flat",
      "wing",
      "balloon",
      "lure",
      "teeth",
      "torpedo",
      "stripe",
      "grace",
      "tiny",
      "slimy",
      "slimy",
      "pink",
      "change",
      "dew",
      "blue",
      "big",
      "bead",
      "crown",
      "neck",
      "crush",
      "squeeze",
      "blink",
      "green",
      "brown",
      "hairy",
      "hourglass",
      "fiddle",
      "harvest",
      "silk",
    ],
  ],
  schoolAndCollege: [
    [
      "pencil",
      "pen",
      "eraser",
      "marker",
      "highlighter",
      "notebook",
      "binder",
      "folder",
      "paper",
      "textbook",
      "workbook",
      "dictionary",
      "thesaurus",
      "atlas",
      "encyclopedia",
      "ruler",
      "protractor",
      "compass",
      "calculator",
      "graph paper",
      "scissors",
      "glue stick",
      "tape",
      "stapler",
      "paper clip",
      "backpack",
      "lunchbox",
      "desk",
      "chair",
      "chalkboard",
      "whiteboard",
      "projector",
      "smartboard",
      "locker",
      "hallway",
      "classroom",
      "library",
      "cafeteria",
      "gymnasium",
      "auditorium",
      "principal",
      "teacher",
      "professor",
      "dean",
      "counselor",
      "student",
      "freshman",
      "sophomore",
      "junior",
      "senior",
      "graduate",
      "alumni",
      "valedictorian",
      "salutatorian",
      "class president",
      "homework",
      "assignment",
      "essay",
      "report",
      "project",
      "presentation",
      "test",
      "quiz",
      "exam",
      "final",
      "midterm",
      "pop quiz",
      "grade",
      "score",
      "report card",
      "gpa",
      "transcript",
      "credit",
      "semester",
      "quarter",
      "syllabus",
      "curriculum",
      "lesson",
      "lecture",
      "tutorial",
      "seminar",
      "lab",
      "workshop",
      "field trip",
      "assembly",
      "recess",
      "lunch",
      "study hall",
      "detention",
      "suspension",
      "expulsion",
      "tardy",
      "absence",
      "truancy",
      "bell",
      "schedule",
      "timetable",
      "period",
      "homeroom",
      "elective",
      "major",
      "minor",
      "degree",
      "diploma",
      "certificate",
      "bachelor",
      "master",
      "doctorate",
      "phd",
      "thesis",
      "dissertation",
      "research",
      "experiment",
      "hypothesis",
      "data",
      "analysis",
      "citation",
      "bibliography",
      "footnote",
      "plagiarism",
      "scholarship",
      "grant",
      "loan",
      "tuition",
      "financial aid",
      "dormitory",
      "dorm",
      "roommate",
      "resident advisor",
      "campus",
      "quad",
      "lecture hall",
      "laboratory",
      "studio",
      "theater",
      "fraternity",
      "sorority",
      "club",
      "society",
      "student government",
      "newspaper",
      "yearbook",
      "magazine",
      "radio station",
      "debate team",
      "chess club",
      "band",
      "orchestra",
      "choir",
      "drama club",
      "football team",
      "basketball team",
      "soccer team",
      "baseball team",
      "track team",
      "coach",
      "mascot",
      "pep rally",
      "homecoming",
      "prom",
      "graduation",
      "commencement",
      "cap",
      "gown",
      "tassel",
      "valedictorian speech",
      "diploma cover",
      "class ring",
      "senior trip",
      "reunion",
      "blackboard eraser",
      "chalk",
      "dry erase marker",
      "overhead projector",
      "document camera",
      "microscope",
      "telescope",
      "bunsen burner",
      "beaker",
      "test tube",
      "periodic table",
      "globe",
      "map",
      "compass rose",
      "flag",
      "alphabet",
      "numbers",
      "multiplication table",
      "spelling bee",
      "science fair",
      "book report",
      "oral report",
      "group project",
      "peer review",
      "extra credit",
      "makeup work",
      "incomplete",
      "pass",
      "fail",
      "honor roll",
      "dean's list",
      "academic probation",
      "summer school",
      "night school",
      "online class",
      "webinar",
      "mooc",
      "zoom",
      "blackboard",
      "canvas",
      "turnitin",
      "quizlet",
      "khan academy",
      "chegg",
      "coursehero",
      "laptop",
      "tablet",
      "chromebook",
      "flash drive",
      "printer",
      "scanner",
      "wifi",
      "password",
      "login",
      "portal",
      "registrar",
      "bursar",
      "admissions",
      "orientation",
      "freshman orientation",
      "advisor",
      "office hours",
      "teaching assistant",
      "tenure",
      "sabbatical",
      "ivy league",
      "community college",
      "state university",
      "liberal arts",
      "trade school",
      "vocational",
      "online degree",
      "accreditation",
      "prerequisite",
      "corequisite",
      "elective course",
      "general education",
      "humanities",
      "science",
      "mathematics",
      "english",
      "history",
      "geography",
      "civics",
      "economics",
      "psychology",
      "sociology",
      "philosophy",
      "literature",
      "writing",
      "algebra",
      "geometry",
      "calculus",
      "statistics",
      "physics",
      "chemistry",
      "biology",
      "anatomy",
      "astronomy",
      "geology",
      "art class",
      "music class",
      "physical education",
      "health class",
      "computer science",
      "foreign language",
      "spanish",
      "french",
      "german",
      "latin",
      "esl",
      "remedial",
      "advanced placement",
      "ap exam",
      "ib program",
      "sat",
      "act",
      "psat",
      "gre",
      "gmat",
      "lsat",
      "mcat",
      "toefl",
      "ielts",
      "placement test",
    ],
    [
      "wood",
      "ink",
      "mistake",
      "broad",
      "neon",
      "spiral",
      "rings",
      "pocket",
      "sheet",
      "heavy",
      "blank",
      "word",
      "synonym",
      "world",
      "volume",
      "straight",
      "angle",
      "circle",
      "math",
      "grid",
      "cut",
      "stick",
      "clear",
      "bind",
      "bend",
      "shoulder",
      "meal",
      "wood",
      "sit",
      "dust",
      "gloss",
      "beam",
      "touch",
      "metal",
      "walk",
      "room",
      "quiet",
      "tray",
      "sweat",
      "stage",
      "boss",
      "chalk",
      "tenure",
      "head",
      "guide",
      "learn",
      "first",
      "second",
      "third",
      "fourth",
      "cap",
      "plural",
      "top",
      "second",
      "lead",
      "night",
      "task",
      "pages",
      "data",
      "build",
      "speak",
      "scantron",
      "short",
      "long",
      "cumulative",
      "half",
      "surprise",
      "letter",
      "number",
      "paper",
      "average",
      "record",
      "unit",
      "half",
      "third",
      "plan",
      "map",
      "teach",
      "talk",
      "help",
      "discuss",
      "coat",
      "hands",
      "bus",
      "gather",
      "play",
      "eat",
      "quiet",
      "punish",
      "remove",
      "gone",
      "late",
      "empty",
      "skip",
      "ring",
      "grid",
      "block",
      "span",
      "home",
      "choice",
      "focus",
      "side",
      "paper",
      "frame",
      "paper",
      "four",
      "six",
      "eight",
      "doctor",
      "book",
      "book",
      "search",
      "test",
      "guess",
      "number",
      "break",
      "source",
      "list",
      "bottom",
      "steal",
      "money",
      "free",
      "borrow",
      "cost",
      "help",
      "brick",
      "sleep",
      "share",
      "mentor",
      "grounds",
      "grass",
      "seats",
      "coat",
      "paint",
      "stage",
      "greek",
      "greek",
      "join",
      "join",
      "lead",
      "print",
      "memory",
      "gloss",
      "air",
      "argue",
      "board",
      "music",
      "strings",
      "sing",
      "act",
      "pigskin",
      "dribble",
      "kick",
      "diamond",
      "run",
      "whistle",
      "costume",
      "spirit",
      "dance",
      "dress",
      "march",
      "speak",
      "square",
      "fabric",
      "swing",
      "speak",
      "leather",
      "stone",
      "beach",
      "decade",
      "felt",
      "dust",
      "smell",
      "transparency",
      "camera",
      "lens",
      "sky",
      "flame",
      "glass",
      "glass",
      "element",
      "sphere",
      "paper",
      "direction",
      "pole",
      "letter",
      "digit",
      "grid",
      "spell",
      "display",
      "read",
      "speak",
      "team",
      "peer",
      "bonus",
      "late",
      "temp",
      "win",
      "lose",
      "list",
      "list",
      "warning",
      "summer",
      "dark",
      "screen",
      "screen",
      "open",
      "call",
      "board",
      "copy",
      "flash",
      "origin",
      "platform",
      "source",
      "portable",
      "slate",
      "key",
      "stick",
      "ink",
      "light",
      "signal",
      "secret",
      "enter",
      "gate",
      "records",
      "money",
      "gate",
      "tour",
      "welcome",
      "guide",
      "door",
      "helper",
      "job",
      "leave",
      "vine",
      "local",
      "public",
      "broad",
      "skill",
      "skill",
      "screen",
      "stamp",
      "before",
      "with",
      "choice",
      "base",
      "people",
      "atom",
      "number",
      "word",
      "past",
      "place",
      "citizen",
      "money",
      "mind",
      "group",
      "think",
      "story",
      "craft",
      "x",
      "shape",
      "curve",
      "data",
      "force",
      "reaction",
      "life",
      "body",
      "star",
      "rock",
      "brush",
      "note",
      "sweat",
      "body",
      "code",
      "tongue",
      "romance",
      "baguettes",
      "beer",
      "rome",
      "second",
      "slow",
      "college",
      "world",
      "college",
      "college",
      "college",
      "college",
      "college",
      "law",
      "doctor",
      "english",
      "english",
      "place",
    ],
  ],
};

export const customWordList = {
  totalRandom: [
    ["one", "two", "three", "four", "five", "six", "seven", "eight"],
    ["isa", "dalawa", "tatlo", "apat", "lima", "anim", "pito", "walo"],
  ],
  // Corruption, politician, economy, culture, tangible, intangible
  thePhilppines: [
    ["one", "two", "three", "four", "five", "six", "seven", "eight"],
    ["isa", "dalawa", "tatlo", "apat", "lima", "anim", "pito", "walo"],
  ],
  insanity: [
    ["one", "two", "three", "four", "five", "six", "seven", "eight"],
    ["isa", "dalawa", "tatlo", "apat", "lima", "anim", "pito", "walo"],
  ],
};
